name: CI

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Run lint
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 0

    steps:
      - name: Checkout source codes
        uses: actions/checkout@v4

      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          install-mode: binary
          args: --timeout=5m --out-format=checkstyle > lint.out

  unittest:
    name: Run unit/benchmark tests
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 0

    steps:
      - name: Checkout source codes
        uses: actions/checkout@v4

      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'

      - name: Unit / Benchmark tests
        run: go test -v ./... -bench=. -coverprofile=coverage.out
